/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccountIcon: typeof import('./../src/views/profile-settings/components/AccountIcon.vue')['default']
    AppleIcon: typeof import('./../src/views/auth/components/AppleIcon.vue')['default']
    ArrowIcon: typeof import('./../src/views/profile-settings/components/ArrowIcon.vue')['default']
    AuthFooter: typeof import('./../src/views/auth/components/AuthFooter.vue')['default']
    AuthHeader: typeof import('./../src/views/auth/components/AuthHeader.vue')['default']
    Compute: typeof import('./../src/components/Compute.vue')['default']
    CreateExercise: typeof import('./../src/components/CreateExercise.vue')['default']
    CreateRoutine: typeof import('./../src/views/routines/components/CreateRoutine.vue')['default']
    DeleteIcon: typeof import('./../src/views/routines/components/icons/DeleteIcon.vue')['default']
    DoneIcon: typeof import('./../src/views/routines/components/icons/DoneIcon.vue')['default']
    DumbellPlaceholder: typeof import('./../src/views/exercises/components/icons/DumbellPlaceholder.vue')['default']
    DuplicateIcon: typeof import('./../src/views/routines/components/icons/DuplicateIcon.vue')['default']
    EditIcon: typeof import('./../src/views/routines/components/icons/EditIcon.vue')['default']
    EditRoutine: typeof import('./../src/views/routines/components/EditRoutine.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    EquipmentIcon: typeof import('./../src/views/exercises/components/icons/EquipmentIcon.vue')['default']
    Exercise: typeof import('./../src/views/routines/components/Exercise.vue')['default']
    ExerciseCard: typeof import('./../src/views/routines/components/ExerciseCard.vue')['default']
    ExerciseCardButtonIcon: typeof import('./../src/views/routines/components/icons/ExerciseCardButtonIcon.vue')['default']
    ExerciseDetailCard: typeof import('./../src/views/exercises/components/ExerciseDetailCard.vue')['default']
    ExercisesIcon: typeof import('./../src/components/icons/ExercisesIcon.vue')['default']
    FacebookIcon: typeof import('./../src/views/auth/components/FacebookIcon.vue')['default']
    FeedIcon: typeof import('./../src/components/icons/FeedIcon.vue')['default']
    Filters: typeof import('./../src/components/Filters.vue')['default']
    GoogleIcon: typeof import('./../src/views/auth/components/GoogleIcon.vue')['default']
    HomeIcon: typeof import('./../src/components/icons/HomeIcon.vue')['default']
    IconLogo: typeof import('~icons/icon/logo')['default']
    IconLogout: typeof import('~icons/icon/logout')['default']
    Logo: typeof import('./../src/views/auth/components/Logo.vue')['default']
    NavBar: typeof import('./../src/components/NavBar.vue')['default']
    NewRoutineIcon: typeof import('./../src/views/routines/components/icons/NewRoutineIcon.vue')['default']
    NoItemsIcon: typeof import('./../src/views/routines/components/icons/NoItemsIcon.vue')['default']
    PlusIcon: typeof import('./../src/views/routines/components/icons/PlusIcon.vue')['default']
    PrimaryIcon: typeof import('./../src/views/exercises/components/icons/PrimaryIcon.vue')['default']
    ProfileIcon: typeof import('./../src/components/icons/ProfileIcon.vue')['default']
    RepsIcon: typeof import('./../src/views/routines/components/icons/RepsIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RoutineDetail: typeof import('./../src/views/routines/components/RoutineDetail.vue')['default']
    RoutinesIcon: typeof import('./../src/components/icons/RoutinesIcon.vue')['default']
    RoutinesItem: typeof import('./../src/views/routines/components/RoutinesItem.vue')['default']
    RoutinesItemButtonIcon: typeof import('./../src/views/routines/components/icons/RoutinesItemButtonIcon.vue')['default']
    RunningMan: typeof import('./../src/components/RunningMan.vue')['default']
    Set: typeof import('./../src/views/routines/components/Set.vue')['default']
    SetsIcon: typeof import('./../src/views/routines/components/icons/SetsIcon.vue')['default']
    SettingsIcon: typeof import('./../src/components/icons/SettingsIcon.vue')['default']
    SocialAuth: typeof import('./../src/views/auth/components/SocialAuth.vue')['default']
    TimerIcon: typeof import('./../src/views/routines/components/icons/TimerIcon.vue')['default']
    WorkoutCard: typeof import('./../src/views/routines/components/WorkoutCard.vue')['default']
    WorkoutLog: typeof import('./../src/views/home/components/WorkoutLog.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
