/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppleIcon: typeof import('./../src/views/auth/components/AppleIcon.vue')['default']
    AuthButton: typeof import('./../src/views/auth/components/AuthButton.vue')['default']
    AuthFooter: typeof import('./../src/views/auth/components/AuthFooter.vue')['default']
    AuthHeader: typeof import('./../src/views/auth/components/AuthHeader.vue')['default']
    Compute: typeof import('./../src/components/Compute.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCaed: typeof import('element-plus/es')['ElCaed']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ExampleViewComponent: typeof import('./../src/views/example-view/components/ExampleViewComponent.vue')['default']
    FacebookIcon: typeof import('./../src/views/auth/components/FacebookIcon.vue')['default']
    GoogleIcon: typeof import('./../src/views/auth/components/GoogleIcon.vue')['default']
    Header: typeof import('./../src/views/auth/components/Header.vue')['default']
    IconCar: typeof import('~icons/icon/car')['default']
    IconCart: typeof import('~icons/icon/cart')['default']
    Logo: typeof import('./../src/views/auth/components/Logo.vue')['default']
    NavBar: typeof import('./../src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RunningMan: typeof import('./../src/components/RunningMan.vue')['default']
    SocialAuth: typeof import('./../src/views/auth/components/SocialAuth.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
