/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    2: typeof import('./../src/components/icons/FeedIcon copy 2.vue')['default']
    3: typeof import('./../src/components/icons/FeedIcon copy 3.vue')['default']
    AccountIcon: typeof import('./../src/views/profile-settings/components/AccountIcon.vue')['default']
    AppleIcon: typeof import('./../src/views/auth/components/AppleIcon.vue')['default']
    ArrowIcon: typeof import('./../src/views/profile-settings/components/ArrowIcon.vue')['default']
    AuthButton: typeof import('./../src/views/auth/components/AuthButton.vue')['default']
    AuthFooter: typeof import('./../src/views/auth/components/AuthFooter.vue')['default']
    AuthHeader: typeof import('./../src/views/auth/components/AuthHeader.vue')['default']
    Compute: typeof import('./../src/components/Compute.vue')['default']
    copy: typeof import('./../src/components/icons/FeedIcon copy.vue')['default']
    DeleteIcon: typeof import('./../src/views/routines/components/icons/DeleteIcon.vue')['default']
    DuplicateIcon: typeof import('./../src/views/routines/components/icons/DuplicateIcon.vue')['default']
    EditIcon: typeof import('./../src/views/routines/components/icons/EditIcon.vue')['default']
    ElButt: typeof import('element-plus/es')['ElButt']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCaed: typeof import('element-plus/es')['ElCaed']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ExampleViewComponent: typeof import('./../src/views/example-view/components/ExampleViewComponent.vue')['default']
    Exercise: typeof import('./../src/views/routines/components/Exercise.vue')['default']
    ExercisesIcon: typeof import('./../src/components/icons/ExercisesIcon.vue')['default']
    Exersise: typeof import('./../src/views/routines/components/Exersise.vue')['default']
    FacebookIcon: typeof import('./../src/views/auth/components/FacebookIcon.vue')['default']
    FeedIcon: typeof import('./../src/components/icons/FeedIcon.vue')['default']
    GoogleIcon: typeof import('./../src/views/auth/components/GoogleIcon.vue')['default']
    Header: typeof import('./../src/views/auth/components/Header.vue')['default']
    IconCar: typeof import('~icons/icon/car')['default']
    IconCart: typeof import('~icons/icon/cart')['default']
    Logo: typeof import('./../src/views/auth/components/Logo.vue')['default']
    LogoutIcon: typeof import('./../src/components/icons/LogoutIcon.vue')['default']
    NavBar: typeof import('./../src/components/NavBar.vue')['default']
    NewRoutineIcon: typeof import('./../src/views/routines/components/icons/NewRoutineIcon.vue')['default']
    ProfileIcon: typeof import('./../src/components/icons/ProfileIcon.vue')['default']
    RepsIcon: typeof import('./../src/views/routines/components/icons/RepsIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Routine: typeof import('./../src/views/routines/components/Routine.vue')['default']
    RoutineDetail: typeof import('./../src/views/routines/components/RoutineDetail.vue')['default']
    RoutinesIcon: typeof import('./../src/components/icons/RoutinesIcon.vue')['default']
    RoutinesItem: typeof import('./../src/views/routines/components/RoutinesItem.vue')['default']
    RoutinesItemButtonIcon: typeof import('./../src/views/routines/components/icons/RoutinesItemButtonIcon.vue')['default']
    RunningMan: typeof import('./../src/components/RunningMan.vue')['default']
    SetsIcon: typeof import('./../src/views/routines/components/icons/SetsIcon.vue')['default']
    SettingsIcon: typeof import('./../src/components/icons/SettingsIcon.vue')['default']
    SocialAuth: typeof import('./../src/views/auth/components/SocialAuth.vue')['default']
    WorkoutLog: typeof import('./../src/views/home/components/WorkoutLog.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
